version: '3.9'

services:
  db:
    container_name: kaminskiy1987-sql
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: kaminskiy1987-db
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: m.kaminskiy@list.ru
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"